#!/bin/bash

card_dir=flashcards

function cleanup {
    rm -r "$card_dir"
}
trap cleanup EXIT

# Split the flashcards into a page per file
mkdir -p "$card_dir"
pdftk flashcards.pdf burst output "$card_dir/page%d.pdf"
rm "$card_dir/doc_data.txt"

num_files="$(ls $card_dir/*.pdf | wc -l)"
num_cards=$((num_files / 2))

# Test
while true ; do
    rand_num=$((RANDOM % num_cards))
    q_card=$((2 * rand_num + 1))
    a_card=$((2 * rand_num + 2))
    mupdf "$card_dir/page$q_card.pdf"
    mupdf "$card_dir/page$a_card.pdf"
done
